// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library catapult.buffers;

import 'dart:typed_data' show Uint8List;

import 'package:flat_buffers/flat_buffers.dart' as fb;

class MosaicProperty {
  MosaicProperty._(this._bc, this._bcOffset);

  factory MosaicProperty(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<MosaicProperty> reader = _MosaicPropertyReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get mosaicPropertyId => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0);

  List<int>? get value => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'MosaicProperty{mosaicPropertyId: ${mosaicPropertyId}, value: ${value}}';
  }
}

class _MosaicPropertyReader extends fb.TableReader<MosaicProperty> {
  const _MosaicPropertyReader();

  @override
  MosaicProperty createObject(fb.BufferContext bc, int offset) => MosaicProperty._(bc, offset);
}

class MosaicPropertyBuilder {
  MosaicPropertyBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addMosaicPropertyId(int? mosaicPropertyId) {
    fbBuilder.addUint8(0, mosaicPropertyId);
    return fbBuilder.offset;
  }

  int addValueOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class MosaicPropertyObjectBuilder extends fb.ObjectBuilder {
  final int? _mosaicPropertyId;
  final List<int>? _value;

  MosaicPropertyObjectBuilder({
    int? mosaicPropertyId,
    List<int>? value,
  })  : _mosaicPropertyId = mosaicPropertyId,
        _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? valueOffset = _value == null ? null : fbBuilder.writeListUint32(_value!);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _mosaicPropertyId);
    fbBuilder.addOffset(1, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class MosaicDefinitionTransactionBuffer {
  MosaicDefinitionTransactionBuffer._(this._bc, this._bcOffset);

  factory MosaicDefinitionTransactionBuffer(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<MosaicDefinitionTransactionBuffer> reader = _MosaicDefinitionTransactionBufferReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get size => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);

  List<int>? get signature => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  List<int>? get signer => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);

  int get version => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);

  int get type => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 12, 0);

  List<int>? get maxFee => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 14);

  List<int>? get deadline => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 16);

  List<int>? get mosaicNonce => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 18);

  List<int>? get mosaicId => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 20);

  int get numOptionalProperties => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 22, 0);

  int get flags => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 24, 0);

  int get divisibility => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 26, 0);

  List<MosaicProperty>? get optionalProperties =>
      const fb.ListReader<MosaicProperty>(MosaicProperty.reader).vTableGetNullable(_bc, _bcOffset, 28);

  @override
  String toString() {
    return 'MosaicDefinitionTransactionBuffer{size: ${size}, signature: ${signature}, signer: ${signer}, version: ${version}, type: ${type}, maxFee: ${maxFee}, deadline: ${deadline}, mosaicNonce: ${mosaicNonce}, mosaicId: ${mosaicId}, numOptionalProperties: ${numOptionalProperties}, flags: ${flags}, divisibility: ${divisibility}, optionalProperties: ${optionalProperties}}';
  }
}

class _MosaicDefinitionTransactionBufferReader extends fb.TableReader<MosaicDefinitionTransactionBuffer> {
  const _MosaicDefinitionTransactionBufferReader();

  @override
  MosaicDefinitionTransactionBuffer createObject(fb.BufferContext bc, int offset) =>
      MosaicDefinitionTransactionBuffer._(bc, offset);
}

class MosaicDefinitionTransactionBufferBuilder {
  MosaicDefinitionTransactionBufferBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(13);
  }

  int addSize(int? size) {
    fbBuilder.addUint32(0, size);
    return fbBuilder.offset;
  }

  int addSignatureOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addSignerOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int addVersion(int? version) {
    fbBuilder.addUint32(3, version);
    return fbBuilder.offset;
  }

  int addType(int? type) {
    fbBuilder.addUint16(4, type);
    return fbBuilder.offset;
  }

  int addMaxFeeOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }

  int addDeadlineOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int addMosaicNonceOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }

  int addMosaicIdOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int addNumOptionalProperties(int? numOptionalProperties) {
    fbBuilder.addUint8(9, numOptionalProperties);
    return fbBuilder.offset;
  }

  int addFlags(int? flags) {
    fbBuilder.addUint8(10, flags);
    return fbBuilder.offset;
  }

  int addDivisibility(int? divisibility) {
    fbBuilder.addUint8(11, divisibility);
    return fbBuilder.offset;
  }

  int addOptionalPropertiesOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class MosaicDefinitionTransactionBufferObjectBuilder extends fb.ObjectBuilder {
  final int? _size;
  final List<int>? _signature;
  final List<int>? _signer;
  final int? _version;
  final int? _type;
  final List<int>? _maxFee;
  final List<int>? _deadline;
  final List<int>? _mosaicNonce;
  final List<int>? _mosaicId;
  final int? _numOptionalProperties;
  final int? _flags;
  final int? _divisibility;
  final List<MosaicPropertyObjectBuilder>? _optionalProperties;

  MosaicDefinitionTransactionBufferObjectBuilder({
    int? size,
    List<int>? signature,
    List<int>? signer,
    int? version,
    int? type,
    List<int>? maxFee,
    List<int>? deadline,
    List<int>? mosaicNonce,
    List<int>? mosaicId,
    int? numOptionalProperties,
    int? flags,
    int? divisibility,
    List<MosaicPropertyObjectBuilder>? optionalProperties,
  })  : _size = size,
        _signature = signature,
        _signer = signer,
        _version = version,
        _type = type,
        _maxFee = maxFee,
        _deadline = deadline,
        _mosaicNonce = mosaicNonce,
        _mosaicId = mosaicId,
        _numOptionalProperties = numOptionalProperties,
        _flags = flags,
        _divisibility = divisibility,
        _optionalProperties = optionalProperties;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? signatureOffset = _signature == null ? null : fbBuilder.writeListUint8(_signature!);
    final int? signerOffset = _signer == null ? null : fbBuilder.writeListUint8(_signer!);
    final int? maxFeeOffset = _maxFee == null ? null : fbBuilder.writeListUint32(_maxFee!);
    final int? deadlineOffset = _deadline == null ? null : fbBuilder.writeListUint32(_deadline!);
    final int? mosaicNonceOffset = _mosaicNonce == null ? null : fbBuilder.writeListUint8(_mosaicNonce!);
    final int? mosaicIdOffset = _mosaicId == null ? null : fbBuilder.writeListUint32(_mosaicId!);
    final int? optionalPropertiesOffset = _optionalProperties == null
        ? null
        : fbBuilder.writeList(_optionalProperties!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(13);
    fbBuilder.addUint32(0, _size);
    fbBuilder.addOffset(1, signatureOffset);
    fbBuilder.addOffset(2, signerOffset);
    fbBuilder.addUint32(3, _version);
    fbBuilder.addUint16(4, _type);
    fbBuilder.addOffset(5, maxFeeOffset);
    fbBuilder.addOffset(6, deadlineOffset);
    fbBuilder.addOffset(7, mosaicNonceOffset);
    fbBuilder.addOffset(8, mosaicIdOffset);
    fbBuilder.addUint8(9, _numOptionalProperties);
    fbBuilder.addUint8(10, _flags);
    fbBuilder.addUint8(11, _divisibility);
    fbBuilder.addOffset(12, optionalPropertiesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
