// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library catapult.buffers;

import 'dart:typed_data' show Uint8List;

import 'package:flat_buffers/flat_buffers.dart' as fb;

class SecretLockTransactionBuffer {
  SecretLockTransactionBuffer._(this._bc, this._bcOffset);

  factory SecretLockTransactionBuffer(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SecretLockTransactionBuffer> reader =
      _SecretLockTransactionBufferReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get size => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);

  List<int>? get signature =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  List<int>? get signer =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);

  int get version => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);

  int get type => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 12, 0);

  List<int>? get maxFee => const fb.ListReader<int>(fb.Uint32Reader())
      .vTableGetNullable(_bc, _bcOffset, 14);

  List<int>? get deadline => const fb.ListReader<int>(fb.Uint32Reader())
      .vTableGetNullable(_bc, _bcOffset, 16);

  List<int>? get mosaicId => const fb.ListReader<int>(fb.Uint32Reader())
      .vTableGetNullable(_bc, _bcOffset, 18);

  List<int>? get mosaicAmount => const fb.ListReader<int>(fb.Uint32Reader())
      .vTableGetNullable(_bc, _bcOffset, 20);

  List<int>? get duration => const fb.ListReader<int>(fb.Uint32Reader())
      .vTableGetNullable(_bc, _bcOffset, 22);

  int get hashAlgorithm =>
      const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 24, 0);

  List<int>? get secret =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 26);

  List<int>? get recipient =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 28);

  @override
  String toString() {
    return 'SecretLockTransactionBuffer{size: ${size}, signature: ${signature}, signer: ${signer}, version: ${version}, type: ${type}, maxFee: ${maxFee}, deadline: ${deadline}, mosaicId: ${mosaicId}, mosaicAmount: ${mosaicAmount}, duration: ${duration}, hashAlgorithm: ${hashAlgorithm}, secret: ${secret}, recipient: ${recipient}}';
  }
}

class _SecretLockTransactionBufferReader
    extends fb.TableReader<SecretLockTransactionBuffer> {
  const _SecretLockTransactionBufferReader();

  @override
  SecretLockTransactionBuffer createObject(fb.BufferContext bc, int offset) =>
      SecretLockTransactionBuffer._(bc, offset);
}

class SecretLockTransactionBufferBuilder {
  SecretLockTransactionBufferBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(13);
  }

  int addSize(int? size) {
    fbBuilder.addUint32(0, size);
    return fbBuilder.offset;
  }

  int addSignatureOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addSignerOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int addVersion(int? version) {
    fbBuilder.addUint32(3, version);
    return fbBuilder.offset;
  }

  int addType(int? type) {
    fbBuilder.addUint16(4, type);
    return fbBuilder.offset;
  }

  int addMaxFeeOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }

  int addDeadlineOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int addMosaicIdOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }

  int addMosaicAmountOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int addDurationOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }

  int addHashAlgorithm(int? hashAlgorithm) {
    fbBuilder.addUint8(10, hashAlgorithm);
    return fbBuilder.offset;
  }

  int addSecretOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }

  int addRecipientOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SecretLockTransactionBufferObjectBuilder extends fb.ObjectBuilder {
  final int? _size;
  final List<int>? _signature;
  final List<int>? _signer;
  final int? _version;
  final int? _type;
  final List<int>? _maxFee;
  final List<int>? _deadline;
  final List<int>? _mosaicId;
  final List<int>? _mosaicAmount;
  final List<int>? _duration;
  final int? _hashAlgorithm;
  final List<int>? _secret;
  final List<int>? _recipient;

  SecretLockTransactionBufferObjectBuilder({
    int? size,
    List<int>? signature,
    List<int>? signer,
    int? version,
    int? type,
    List<int>? maxFee,
    List<int>? deadline,
    List<int>? mosaicId,
    List<int>? mosaicAmount,
    List<int>? duration,
    int? hashAlgorithm,
    List<int>? secret,
    List<int>? recipient,
  })  : _size = size,
        _signature = signature,
        _signer = signer,
        _version = version,
        _type = type,
        _maxFee = maxFee,
        _deadline = deadline,
        _mosaicId = mosaicId,
        _mosaicAmount = mosaicAmount,
        _duration = duration,
        _hashAlgorithm = hashAlgorithm,
        _secret = secret,
        _recipient = recipient;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? signatureOffset =
        _signature == null ? null : fbBuilder.writeListUint8(_signature!);
    final int? signerOffset =
        _signer == null ? null : fbBuilder.writeListUint8(_signer!);
    final int? maxFeeOffset =
        _maxFee == null ? null : fbBuilder.writeListUint32(_maxFee!);
    final int? deadlineOffset =
        _deadline == null ? null : fbBuilder.writeListUint32(_deadline!);
    final int? mosaicIdOffset =
        _mosaicId == null ? null : fbBuilder.writeListUint32(_mosaicId!);
    final int? mosaicAmountOffset = _mosaicAmount == null
        ? null
        : fbBuilder.writeListUint32(_mosaicAmount!);
    final int? durationOffset =
        _duration == null ? null : fbBuilder.writeListUint32(_duration!);
    final int? secretOffset =
        _secret == null ? null : fbBuilder.writeListUint8(_secret!);
    final int? recipientOffset =
        _recipient == null ? null : fbBuilder.writeListUint8(_recipient!);
    fbBuilder.startTable(13);
    fbBuilder.addUint32(0, _size);
    fbBuilder.addOffset(1, signatureOffset);
    fbBuilder.addOffset(2, signerOffset);
    fbBuilder.addUint32(3, _version);
    fbBuilder.addUint16(4, _type);
    fbBuilder.addOffset(5, maxFeeOffset);
    fbBuilder.addOffset(6, deadlineOffset);
    fbBuilder.addOffset(7, mosaicIdOffset);
    fbBuilder.addOffset(8, mosaicAmountOffset);
    fbBuilder.addOffset(9, durationOffset);
    fbBuilder.addUint8(10, _hashAlgorithm);
    fbBuilder.addOffset(11, secretOffset);
    fbBuilder.addOffset(12, recipientOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
