// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library catapult.buffers;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;
import './schema_mosaic_buffer.dart';

class DeployContractTransactionBuffer {
  DeployContractTransactionBuffer._(this._bc, this._bcOffset);
  factory DeployContractTransactionBuffer(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DeployContractTransactionBuffer> reader = _DeployContractTransactionBufferReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get size => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<int>? get signature => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);
  List<int>? get signer => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get version => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);
  int get type => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 12, 0);
  List<int>? get maxFee => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 14);
  List<int>? get deadline => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 16);
  List<int>? get driveKey => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 18);
  List<int>? get fileNameSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 20);
  List<int>? get functionNameSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 22);
  List<int>? get actualArgumentsSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 24);
  List<int>? get executionCallPayment => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 26);
  List<int>? get downloadCallPayment => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 28);
  int get servicePaymentsCount => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 30, 0);
  List<int>? get automaticExecutionFileNameSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 32);
  List<int>? get automaticExecutionFunctionNameSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 34);
  List<int>? get automaticExecutionCallPayment => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 36);
  List<int>? get automaticDownloadCallPayment => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 38);
  int get automaticExecutionsNumber => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 40, 0);
  List<int>? get assignee => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 42);
  List<int>? get fileName => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 44);
  List<int>? get functionName => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 46);
  List<int>? get actualArguments => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 48);
  List<MosaicBuffer>? get servicePayments => const fb.ListReader<MosaicBuffer>(MosaicBuffer.reader).vTableGetNullable(_bc, _bcOffset, 50);
  List<int>? get automaticExecutionFileName => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 52);
  List<int>? get automaticExecutionFunctionName => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 54);

  @override
  String toString() {
    return 'DeployContractTransactionBuffer{size: ${size}, signature: ${signature}, signer: ${signer}, version: ${version}, type: ${type}, maxFee: ${maxFee}, deadline: ${deadline}, driveKey: ${driveKey}, fileNameSize: ${fileNameSize}, functionNameSize: ${functionNameSize}, actualArgumentsSize: ${actualArgumentsSize}, executionCallPayment: ${executionCallPayment}, downloadCallPayment: ${downloadCallPayment}, servicePaymentsCount: ${servicePaymentsCount}, automaticExecutionFileNameSize: ${automaticExecutionFileNameSize}, automaticExecutionFunctionNameSize: ${automaticExecutionFunctionNameSize}, automaticExecutionCallPayment: ${automaticExecutionCallPayment}, automaticDownloadCallPayment: ${automaticDownloadCallPayment}, automaticExecutionsNumber: ${automaticExecutionsNumber}, assignee: ${assignee}, fileName: ${fileName}, functionName: ${functionName}, actualArguments: ${actualArguments}, servicePayments: ${servicePayments}, automaticExecutionFileName: ${automaticExecutionFileName}, automaticExecutionFunctionName: ${automaticExecutionFunctionName}}';
  }
}

class _DeployContractTransactionBufferReader extends fb.TableReader<DeployContractTransactionBuffer> {
  const _DeployContractTransactionBufferReader();

  @override
  DeployContractTransactionBuffer createObject(fb.BufferContext bc, int offset) => 
    DeployContractTransactionBuffer._(bc, offset);
}

class DeployContractTransactionBufferBuilder {
  DeployContractTransactionBufferBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(26);
  }

  int addSize(int? size) {
    fbBuilder.addUint32(0, size);
    return fbBuilder.offset;
  }
  int addSignatureOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addSignerOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addVersion(int? version) {
    fbBuilder.addUint32(3, version);
    return fbBuilder.offset;
  }
  int addType(int? type) {
    fbBuilder.addUint16(4, type);
    return fbBuilder.offset;
  }
  int addMaxFeeOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addDeadlineOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addDriveKeyOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addFileNameSizeOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addFunctionNameSizeOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addActualArgumentsSizeOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addExecutionCallPaymentOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }
  int addDownloadCallPaymentOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }
  int addServicePaymentsCount(int? servicePaymentsCount) {
    fbBuilder.addUint8(13, servicePaymentsCount);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionFileNameSizeOffset(int? offset) {
    fbBuilder.addOffset(14, offset);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionFunctionNameSizeOffset(int? offset) {
    fbBuilder.addOffset(15, offset);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionCallPaymentOffset(int? offset) {
    fbBuilder.addOffset(16, offset);
    return fbBuilder.offset;
  }
  int addAutomaticDownloadCallPaymentOffset(int? offset) {
    fbBuilder.addOffset(17, offset);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionsNumber(int? automaticExecutionsNumber) {
    fbBuilder.addUint32(18, automaticExecutionsNumber);
    return fbBuilder.offset;
  }
  int addAssigneeOffset(int? offset) {
    fbBuilder.addOffset(19, offset);
    return fbBuilder.offset;
  }
  int addFileNameOffset(int? offset) {
    fbBuilder.addOffset(20, offset);
    return fbBuilder.offset;
  }
  int addFunctionNameOffset(int? offset) {
    fbBuilder.addOffset(21, offset);
    return fbBuilder.offset;
  }
  int addActualArgumentsOffset(int? offset) {
    fbBuilder.addOffset(22, offset);
    return fbBuilder.offset;
  }
  int addServicePaymentsOffset(int? offset) {
    fbBuilder.addOffset(23, offset);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionFileNameOffset(int? offset) {
    fbBuilder.addOffset(24, offset);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionFunctionNameOffset(int? offset) {
    fbBuilder.addOffset(25, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DeployContractTransactionBufferObjectBuilder extends fb.ObjectBuilder {
  final int? _size;
  final List<int>? _signature;
  final List<int>? _signer;
  final int? _version;
  final int? _type;
  final List<int>? _maxFee;
  final List<int>? _deadline;
  final List<int>? _driveKey;
  final List<int>? _fileNameSize;
  final List<int>? _functionNameSize;
  final List<int>? _actualArgumentsSize;
  final List<int>? _executionCallPayment;
  final List<int>? _downloadCallPayment;
  final int? _servicePaymentsCount;
  final List<int>? _automaticExecutionFileNameSize;
  final List<int>? _automaticExecutionFunctionNameSize;
  final List<int>? _automaticExecutionCallPayment;
  final List<int>? _automaticDownloadCallPayment;
  final int? _automaticExecutionsNumber;
  final List<int>? _assignee;
  final List<int>? _fileName;
  final List<int>? _functionName;
  final List<int>? _actualArguments;
  final List<MosaicBufferObjectBuilder>? _servicePayments;
  final List<int>? _automaticExecutionFileName;
  final List<int>? _automaticExecutionFunctionName;

  DeployContractTransactionBufferObjectBuilder({
    int? size,
    List<int>? signature,
    List<int>? signer,
    int? version,
    int? type,
    List<int>? maxFee,
    List<int>? deadline,
    List<int>? driveKey,
    List<int>? fileNameSize,
    List<int>? functionNameSize,
    List<int>? actualArgumentsSize,
    List<int>? executionCallPayment,
    List<int>? downloadCallPayment,
    int? servicePaymentsCount,
    List<int>? automaticExecutionFileNameSize,
    List<int>? automaticExecutionFunctionNameSize,
    List<int>? automaticExecutionCallPayment,
    List<int>? automaticDownloadCallPayment,
    int? automaticExecutionsNumber,
    List<int>? assignee,
    List<int>? fileName,
    List<int>? functionName,
    List<int>? actualArguments,
    List<MosaicBufferObjectBuilder>? servicePayments,
    List<int>? automaticExecutionFileName,
    List<int>? automaticExecutionFunctionName,
  })
      : _size = size,
        _signature = signature,
        _signer = signer,
        _version = version,
        _type = type,
        _maxFee = maxFee,
        _deadline = deadline,
        _driveKey = driveKey,
        _fileNameSize = fileNameSize,
        _functionNameSize = functionNameSize,
        _actualArgumentsSize = actualArgumentsSize,
        _executionCallPayment = executionCallPayment,
        _downloadCallPayment = downloadCallPayment,
        _servicePaymentsCount = servicePaymentsCount,
        _automaticExecutionFileNameSize = automaticExecutionFileNameSize,
        _automaticExecutionFunctionNameSize = automaticExecutionFunctionNameSize,
        _automaticExecutionCallPayment = automaticExecutionCallPayment,
        _automaticDownloadCallPayment = automaticDownloadCallPayment,
        _automaticExecutionsNumber = automaticExecutionsNumber,
        _assignee = assignee,
        _fileName = fileName,
        _functionName = functionName,
        _actualArguments = actualArguments,
        _servicePayments = servicePayments,
        _automaticExecutionFileName = automaticExecutionFileName,
        _automaticExecutionFunctionName = automaticExecutionFunctionName;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? signatureOffset = _signature == null ? null
        : fbBuilder.writeListUint8(_signature!);
    final int? signerOffset = _signer == null ? null
        : fbBuilder.writeListUint8(_signer!);
    final int? maxFeeOffset = _maxFee == null ? null
        : fbBuilder.writeListUint32(_maxFee!);
    final int? deadlineOffset = _deadline == null ? null
        : fbBuilder.writeListUint32(_deadline!);
    final int? driveKeyOffset = _driveKey == null ? null
        : fbBuilder.writeListUint8(_driveKey!);
    final int? fileNameSizeOffset = _fileNameSize == null ? null
        : fbBuilder.writeListUint8(_fileNameSize!);
    final int? functionNameSizeOffset = _functionNameSize == null ? null
        : fbBuilder.writeListUint8(_functionNameSize!);
    final int? actualArgumentsSizeOffset = _actualArgumentsSize == null ? null
        : fbBuilder.writeListUint8(_actualArgumentsSize!);
    final int? executionCallPaymentOffset = _executionCallPayment == null ? null
        : fbBuilder.writeListUint32(_executionCallPayment!);
    final int? downloadCallPaymentOffset = _downloadCallPayment == null ? null
        : fbBuilder.writeListUint32(_downloadCallPayment!);
    final int? automaticExecutionFileNameSizeOffset = _automaticExecutionFileNameSize == null ? null
        : fbBuilder.writeListUint8(_automaticExecutionFileNameSize!);
    final int? automaticExecutionFunctionNameSizeOffset = _automaticExecutionFunctionNameSize == null ? null
        : fbBuilder.writeListUint8(_automaticExecutionFunctionNameSize!);
    final int? automaticExecutionCallPaymentOffset = _automaticExecutionCallPayment == null ? null
        : fbBuilder.writeListUint32(_automaticExecutionCallPayment!);
    final int? automaticDownloadCallPaymentOffset = _automaticDownloadCallPayment == null ? null
        : fbBuilder.writeListUint32(_automaticDownloadCallPayment!);
    final int? assigneeOffset = _assignee == null ? null
        : fbBuilder.writeListUint8(_assignee!);
    final int? fileNameOffset = _fileName == null ? null
        : fbBuilder.writeListUint8(_fileName!);
    final int? functionNameOffset = _functionName == null ? null
        : fbBuilder.writeListUint8(_functionName!);
    final int? actualArgumentsOffset = _actualArguments == null ? null
        : fbBuilder.writeListUint8(_actualArguments!);
    final int? servicePaymentsOffset = _servicePayments == null ? null
        : fbBuilder.writeList(_servicePayments!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? automaticExecutionFileNameOffset = _automaticExecutionFileName == null ? null
        : fbBuilder.writeListUint8(_automaticExecutionFileName!);
    final int? automaticExecutionFunctionNameOffset = _automaticExecutionFunctionName == null ? null
        : fbBuilder.writeListUint8(_automaticExecutionFunctionName!);
    fbBuilder.startTable(26);
    fbBuilder.addUint32(0, _size);
    fbBuilder.addOffset(1, signatureOffset);
    fbBuilder.addOffset(2, signerOffset);
    fbBuilder.addUint32(3, _version);
    fbBuilder.addUint16(4, _type);
    fbBuilder.addOffset(5, maxFeeOffset);
    fbBuilder.addOffset(6, deadlineOffset);
    fbBuilder.addOffset(7, driveKeyOffset);
    fbBuilder.addOffset(8, fileNameSizeOffset);
    fbBuilder.addOffset(9, functionNameSizeOffset);
    fbBuilder.addOffset(10, actualArgumentsSizeOffset);
    fbBuilder.addOffset(11, executionCallPaymentOffset);
    fbBuilder.addOffset(12, downloadCallPaymentOffset);
    fbBuilder.addUint8(13, _servicePaymentsCount);
    fbBuilder.addOffset(14, automaticExecutionFileNameSizeOffset);
    fbBuilder.addOffset(15, automaticExecutionFunctionNameSizeOffset);
    fbBuilder.addOffset(16, automaticExecutionCallPaymentOffset);
    fbBuilder.addOffset(17, automaticDownloadCallPaymentOffset);
    fbBuilder.addUint32(18, _automaticExecutionsNumber);
    fbBuilder.addOffset(19, assigneeOffset);
    fbBuilder.addOffset(20, fileNameOffset);
    fbBuilder.addOffset(21, functionNameOffset);
    fbBuilder.addOffset(22, actualArgumentsOffset);
    fbBuilder.addOffset(23, servicePaymentsOffset);
    fbBuilder.addOffset(24, automaticExecutionFileNameOffset);
    fbBuilder.addOffset(25, automaticExecutionFunctionNameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class AutomaticExecutionsPaymentTransactionBuffer {
  AutomaticExecutionsPaymentTransactionBuffer._(this._bc, this._bcOffset);
  factory AutomaticExecutionsPaymentTransactionBuffer(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<AutomaticExecutionsPaymentTransactionBuffer> reader = _AutomaticExecutionsPaymentTransactionBufferReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get size => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<int>? get signature => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);
  List<int>? get signer => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get version => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);
  int get type => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 12, 0);
  List<int>? get maxFee => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 14);
  List<int>? get deadline => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 16);
  List<int>? get contractKey => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 18);
  int get automaticExecutionsNumber => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 20, 0);

  @override
  String toString() {
    return 'AutomaticExecutionsPaymentTransactionBuffer{size: ${size}, signature: ${signature}, signer: ${signer}, version: ${version}, type: ${type}, maxFee: ${maxFee}, deadline: ${deadline}, contractKey: ${contractKey}, automaticExecutionsNumber: ${automaticExecutionsNumber}}';
  }
}

class _AutomaticExecutionsPaymentTransactionBufferReader extends fb.TableReader<AutomaticExecutionsPaymentTransactionBuffer> {
  const _AutomaticExecutionsPaymentTransactionBufferReader();

  @override
  AutomaticExecutionsPaymentTransactionBuffer createObject(fb.BufferContext bc, int offset) => 
    AutomaticExecutionsPaymentTransactionBuffer._(bc, offset);
}

class AutomaticExecutionsPaymentTransactionBufferBuilder {
  AutomaticExecutionsPaymentTransactionBufferBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(9);
  }

  int addSize(int? size) {
    fbBuilder.addUint32(0, size);
    return fbBuilder.offset;
  }
  int addSignatureOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addSignerOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addVersion(int? version) {
    fbBuilder.addUint32(3, version);
    return fbBuilder.offset;
  }
  int addType(int? type) {
    fbBuilder.addUint16(4, type);
    return fbBuilder.offset;
  }
  int addMaxFeeOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addDeadlineOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addContractKeyOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addAutomaticExecutionsNumber(int? automaticExecutionsNumber) {
    fbBuilder.addUint32(8, automaticExecutionsNumber);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class AutomaticExecutionsPaymentTransactionBufferObjectBuilder extends fb.ObjectBuilder {
  final int? _size;
  final List<int>? _signature;
  final List<int>? _signer;
  final int? _version;
  final int? _type;
  final List<int>? _maxFee;
  final List<int>? _deadline;
  final List<int>? _contractKey;
  final int? _automaticExecutionsNumber;

  AutomaticExecutionsPaymentTransactionBufferObjectBuilder({
    int? size,
    List<int>? signature,
    List<int>? signer,
    int? version,
    int? type,
    List<int>? maxFee,
    List<int>? deadline,
    List<int>? contractKey,
    int? automaticExecutionsNumber,
  })
      : _size = size,
        _signature = signature,
        _signer = signer,
        _version = version,
        _type = type,
        _maxFee = maxFee,
        _deadline = deadline,
        _contractKey = contractKey,
        _automaticExecutionsNumber = automaticExecutionsNumber;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? signatureOffset = _signature == null ? null
        : fbBuilder.writeListUint8(_signature!);
    final int? signerOffset = _signer == null ? null
        : fbBuilder.writeListUint8(_signer!);
    final int? maxFeeOffset = _maxFee == null ? null
        : fbBuilder.writeListUint32(_maxFee!);
    final int? deadlineOffset = _deadline == null ? null
        : fbBuilder.writeListUint32(_deadline!);
    final int? contractKeyOffset = _contractKey == null ? null
        : fbBuilder.writeListUint8(_contractKey!);
    fbBuilder.startTable(9);
    fbBuilder.addUint32(0, _size);
    fbBuilder.addOffset(1, signatureOffset);
    fbBuilder.addOffset(2, signerOffset);
    fbBuilder.addUint32(3, _version);
    fbBuilder.addUint16(4, _type);
    fbBuilder.addOffset(5, maxFeeOffset);
    fbBuilder.addOffset(6, deadlineOffset);
    fbBuilder.addOffset(7, contractKeyOffset);
    fbBuilder.addUint32(8, _automaticExecutionsNumber);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class ManualCallTransactionBuffer {
  ManualCallTransactionBuffer._(this._bc, this._bcOffset);
  factory ManualCallTransactionBuffer(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ManualCallTransactionBuffer> reader = _ManualCallTransactionBufferReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get size => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<int>? get signature => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);
  List<int>? get signer => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get version => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);
  int get type => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 12, 0);
  List<int>? get maxFee => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 14);
  List<int>? get deadline => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 16);
  List<int>? get contractKey => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 18);
  List<int>? get fileNameSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 20);
  List<int>? get functionNameSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 22);
  List<int>? get actualArgumentsSize => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 24);
  List<int>? get executionCallPayment => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 26);
  List<int>? get downloadCallPayment => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 28);
  int get servicePaymentsCount => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 30, 0);
  List<int>? get fileName => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 32);
  List<int>? get functionName => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 34);
  List<int>? get actualArguments => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 36);
  List<MosaicBuffer>? get servicePayments => const fb.ListReader<MosaicBuffer>(MosaicBuffer.reader).vTableGetNullable(_bc, _bcOffset, 38);

  @override
  String toString() {
    return 'ManualCallTransactionBuffer{size: ${size}, signature: ${signature}, signer: ${signer}, version: ${version}, type: ${type}, maxFee: ${maxFee}, deadline: ${deadline}, contractKey: ${contractKey}, fileNameSize: ${fileNameSize}, functionNameSize: ${functionNameSize}, actualArgumentsSize: ${actualArgumentsSize}, executionCallPayment: ${executionCallPayment}, downloadCallPayment: ${downloadCallPayment}, servicePaymentsCount: ${servicePaymentsCount}, fileName: ${fileName}, functionName: ${functionName}, actualArguments: ${actualArguments}, servicePayments: ${servicePayments}}';
  }
}

class _ManualCallTransactionBufferReader extends fb.TableReader<ManualCallTransactionBuffer> {
  const _ManualCallTransactionBufferReader();

  @override
  ManualCallTransactionBuffer createObject(fb.BufferContext bc, int offset) => 
    ManualCallTransactionBuffer._(bc, offset);
}

class ManualCallTransactionBufferBuilder {
  ManualCallTransactionBufferBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(18);
  }

  int addSize(int? size) {
    fbBuilder.addUint32(0, size);
    return fbBuilder.offset;
  }
  int addSignatureOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addSignerOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addVersion(int? version) {
    fbBuilder.addUint32(3, version);
    return fbBuilder.offset;
  }
  int addType(int? type) {
    fbBuilder.addUint16(4, type);
    return fbBuilder.offset;
  }
  int addMaxFeeOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addDeadlineOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addContractKeyOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addFileNameSizeOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addFunctionNameSizeOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addActualArgumentsSizeOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addExecutionCallPaymentOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }
  int addDownloadCallPaymentOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }
  int addServicePaymentsCount(int? servicePaymentsCount) {
    fbBuilder.addUint8(13, servicePaymentsCount);
    return fbBuilder.offset;
  }
  int addFileNameOffset(int? offset) {
    fbBuilder.addOffset(14, offset);
    return fbBuilder.offset;
  }
  int addFunctionNameOffset(int? offset) {
    fbBuilder.addOffset(15, offset);
    return fbBuilder.offset;
  }
  int addActualArgumentsOffset(int? offset) {
    fbBuilder.addOffset(16, offset);
    return fbBuilder.offset;
  }
  int addServicePaymentsOffset(int? offset) {
    fbBuilder.addOffset(17, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ManualCallTransactionBufferObjectBuilder extends fb.ObjectBuilder {
  final int? _size;
  final List<int>? _signature;
  final List<int>? _signer;
  final int? _version;
  final int? _type;
  final List<int>? _maxFee;
  final List<int>? _deadline;
  final List<int>? _contractKey;
  final List<int>? _fileNameSize;
  final List<int>? _functionNameSize;
  final List<int>? _actualArgumentsSize;
  final List<int>? _executionCallPayment;
  final List<int>? _downloadCallPayment;
  final int? _servicePaymentsCount;
  final List<int>? _fileName;
  final List<int>? _functionName;
  final List<int>? _actualArguments;
  final List<MosaicBufferObjectBuilder>? _servicePayments;

  ManualCallTransactionBufferObjectBuilder({
    int? size,
    List<int>? signature,
    List<int>? signer,
    int? version,
    int? type,
    List<int>? maxFee,
    List<int>? deadline,
    List<int>? contractKey,
    List<int>? fileNameSize,
    List<int>? functionNameSize,
    List<int>? actualArgumentsSize,
    List<int>? executionCallPayment,
    List<int>? downloadCallPayment,
    int? servicePaymentsCount,
    List<int>? fileName,
    List<int>? functionName,
    List<int>? actualArguments,
    List<MosaicBufferObjectBuilder>? servicePayments,
  })
      : _size = size,
        _signature = signature,
        _signer = signer,
        _version = version,
        _type = type,
        _maxFee = maxFee,
        _deadline = deadline,
        _contractKey = contractKey,
        _fileNameSize = fileNameSize,
        _functionNameSize = functionNameSize,
        _actualArgumentsSize = actualArgumentsSize,
        _executionCallPayment = executionCallPayment,
        _downloadCallPayment = downloadCallPayment,
        _servicePaymentsCount = servicePaymentsCount,
        _fileName = fileName,
        _functionName = functionName,
        _actualArguments = actualArguments,
        _servicePayments = servicePayments;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? signatureOffset = _signature == null ? null
        : fbBuilder.writeListUint8(_signature!);
    final int? signerOffset = _signer == null ? null
        : fbBuilder.writeListUint8(_signer!);
    final int? maxFeeOffset = _maxFee == null ? null
        : fbBuilder.writeListUint32(_maxFee!);
    final int? deadlineOffset = _deadline == null ? null
        : fbBuilder.writeListUint32(_deadline!);
    final int? contractKeyOffset = _contractKey == null ? null
        : fbBuilder.writeListUint8(_contractKey!);
    final int? fileNameSizeOffset = _fileNameSize == null ? null
        : fbBuilder.writeListUint8(_fileNameSize!);
    final int? functionNameSizeOffset = _functionNameSize == null ? null
        : fbBuilder.writeListUint8(_functionNameSize!);
    final int? actualArgumentsSizeOffset = _actualArgumentsSize == null ? null
        : fbBuilder.writeListUint8(_actualArgumentsSize!);
    final int? executionCallPaymentOffset = _executionCallPayment == null ? null
        : fbBuilder.writeListUint32(_executionCallPayment!);
    final int? downloadCallPaymentOffset = _downloadCallPayment == null ? null
        : fbBuilder.writeListUint32(_downloadCallPayment!);
    final int? fileNameOffset = _fileName == null ? null
        : fbBuilder.writeListUint8(_fileName!);
    final int? functionNameOffset = _functionName == null ? null
        : fbBuilder.writeListUint8(_functionName!);
    final int? actualArgumentsOffset = _actualArguments == null ? null
        : fbBuilder.writeListUint8(_actualArguments!);
    final int? servicePaymentsOffset = _servicePayments == null ? null
        : fbBuilder.writeList(_servicePayments!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(18);
    fbBuilder.addUint32(0, _size);
    fbBuilder.addOffset(1, signatureOffset);
    fbBuilder.addOffset(2, signerOffset);
    fbBuilder.addUint32(3, _version);
    fbBuilder.addUint16(4, _type);
    fbBuilder.addOffset(5, maxFeeOffset);
    fbBuilder.addOffset(6, deadlineOffset);
    fbBuilder.addOffset(7, contractKeyOffset);
    fbBuilder.addOffset(8, fileNameSizeOffset);
    fbBuilder.addOffset(9, functionNameSizeOffset);
    fbBuilder.addOffset(10, actualArgumentsSizeOffset);
    fbBuilder.addOffset(11, executionCallPaymentOffset);
    fbBuilder.addOffset(12, downloadCallPaymentOffset);
    fbBuilder.addUint8(13, _servicePaymentsCount);
    fbBuilder.addOffset(14, fileNameOffset);
    fbBuilder.addOffset(15, functionNameOffset);
    fbBuilder.addOffset(16, actualArgumentsOffset);
    fbBuilder.addOffset(17, servicePaymentsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
