name: Publish sdk

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    container:
      image: dart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup credentials
        env:
          CREDENTIALS_JSON: ${{ secrets.PUB_CREDENTIALS_JSON}}
        run: |
          mkdir -p $HOME/.config/dart/
          echo $CREDENTIALS_JSON > $HOME/.config/dart/pub-credentials.json
          
      - name: Publish package
        run: dart pub publish -f
